In [1]:
import pandas as pd
import numpy as np

In [409]:
data = np.random.randint(5, size=(10, 10))
data[1, 2] = np.nan

ValueError: cannot convert float NaN to integer

In [339]:
def comput_cost(data, p, q , b):
    return np.sum(np.sum((data - (p@q.T + b ))**2))*0.01

In [395]:
def gradient(data, p, q , b):
    p_new =  p + 0.003*(data - (p@q.T + b))@q
    q_new = q + 0.003*(data - (p@q.T + b))@p
    b_new = b + 0.003*(data - (p@q.T + b))
    return p_new, q_new , b_new

In [396]:
p = np.random.rand(10, 2)
q = np.random.rand(10, 2)  
b = np.random.rand(10, 1)
p@q.T + b

array([[0.77805191, 1.027759  , 0.46623186, 0.3429668 , 1.20849869,
        0.6676211 , 1.2133218 , 1.20409552, 0.53698931, 0.58250818],
       [1.00142048, 1.07071268, 0.9223594 , 0.89119049, 1.10833926,
        0.96989288, 1.11138446, 1.10985745, 0.94077003, 0.94148864],
       [0.95617949, 1.0809294 , 0.43422188, 0.22373937, 1.78556164,
        0.94434627, 1.70427108, 1.64899397, 0.52960125, 1.13652093],
       [0.59160529, 0.85783886, 0.26416357, 0.13477997, 1.0421257 ,
        0.47327219, 1.04841449, 1.0392716 , 0.33878175, 0.37931148],
       [1.6697914 , 1.77311761, 1.15908162, 0.95286983, 2.48825582,
        1.66926758, 2.40300738, 2.34637645, 1.25093216, 1.87868213],
       [1.45155327, 1.65736722, 1.10096517, 0.96131466, 1.96333532,
        1.37160875, 1.94592043, 1.9253674 , 1.17462611, 1.36143512],
       [0.7976935 , 0.6314243 , 0.5407171 , 0.43386881, 1.29054644,
        0.92620962, 1.18113656, 1.12299283, 0.5697686 , 1.28066376],
       [0.68389566, 0.88238421, 0.3232528

In [404]:
for _ in range(1000):
    p, q, b= gradient(data, p, q, b)

In [388]:
p , q = gradient(data, p, q)
p

array([[1.0928405 , 0.28699818],
       [0.75934101, 0.69059174],
       [0.54053408, 0.75777665],
       [1.08059032, 0.0478681 ],
       [1.01077752, 0.59456705],
       [0.92125559, 0.08312245],
       [0.99672867, 0.1353131 ],
       [0.3844755 , 0.34657908],
       [0.81355072, 0.47358065],
       [0.9055484 , 0.54748031]])

In [405]:
comput_cost(data, p, q)

2.6556169630658935

In [406]:
p@q.T + b

array([[0.14802988, 1.0265586 , 3.02719522, 3.97258511, 1.17605327,
        3.00681607, 3.82900172, 2.85234702, 2.88894568, 2.89114065],
       [1.98046529, 1.98654609, 3.03537964, 3.00184202, 3.97433969,
        1.12117757, 1.97707164, 1.96855654, 1.96929199, 1.96075329],
       [3.84791905, 1.01946403, 3.95007867, 2.08095271, 3.95073712,
        0.17421137, 0.07820262, 2.84802477, 0.0764378 , 2.85431801],
       [1.12199163, 1.92663389, 2.0097573 , 3.96243518, 0.1681462 ,
        2.05137715, 1.95174224, 1.86955238, 2.87967263, 3.83190125],
       [2.00991203, 3.85774577, 3.0503737 , 2.10602166, 3.98167335,
        1.13867404, 1.04738659, 1.96158762, 3.8474262 , 3.82759223],
       [1.07864151, 1.01799023, 2.91403583, 0.16151797, 0.1172502 ,
        3.86157889, 1.02606063, 1.9225357 , 3.82904581, 3.82437863],
       [4.00106705, 0.07951769, 3.81988612, 2.12027043, 0.10331013,
        3.89929308, 1.98151395, 0.92941389, 0.1162316 , 3.83954832],
       [0.05312773, 3.77443089, 0.1227763