In [1]:
import pandas as pd
import numpy as np


In [2]:
data = np.random.randint(5, size=(10, 10))
data


array([[2, 4, 3, 1, 4, 0, 0, 3, 3, 3],
       [1, 2, 3, 0, 0, 2, 3, 4, 3, 4],
       [2, 2, 2, 2, 1, 2, 0, 1, 1, 4],
       [0, 3, 3, 1, 2, 0, 2, 3, 3, 4],
       [3, 1, 0, 0, 4, 3, 3, 2, 3, 4],
       [2, 3, 0, 4, 2, 3, 3, 4, 3, 0],
       [0, 0, 3, 3, 2, 2, 4, 0, 2, 2],
       [3, 4, 1, 1, 0, 3, 4, 3, 2, 2],
       [0, 4, 4, 1, 3, 3, 2, 4, 0, 1],
       [4, 3, 1, 0, 0, 2, 3, 2, 2, 3]])

In [17]:
def comput_cost(data, p, q , b):
    return np.sum(np.sum((data - (p@q.T + b ))**2))/(len(data))**2


In [18]:
def gradient(data, p, q , b):
    p_new =  p + 0.03*(data - (p@q.T + b))@q
    q_new = q + 0.03*(data - (p@q.T + b))@p
    b_new = b + 0.03*(data - (p@q.T + b))
    return p_new, q_new , b_new


In [19]:
p = np.random.rand(10, 2)
q = np.random.rand(10, 2)  
b = np.random.rand(10, 1)
p@q.T + b


array([[0.61806239, 0.53516507, 0.69600067, 0.66578859, 0.69411375,
        0.65803437, 0.53515276, 0.45828002, 0.44299003, 0.69292984],
       [1.3463814 , 0.78148248, 1.26400003, 1.43400143, 1.36897007,
        1.05100347, 1.20568968, 0.9777674 , 0.78722827, 1.3319536 ],
       [1.79307305, 1.24313405, 1.59906982, 1.83429587, 1.72311746,
        1.40019559, 1.73481433, 1.56782242, 1.36631175, 1.68171121],
       [1.12386197, 0.69646311, 0.97727441, 1.15752093, 1.07287699,
        0.82240228, 1.07568906, 0.94388751, 0.78786775, 1.04089465],
       [0.94245322, 0.73583653, 0.99306715, 1.00577429, 1.01595259,
        0.90914392, 0.83514989, 0.71283677, 0.65451012, 1.00622366],
       [1.56651795, 1.29871763, 1.72191611, 1.68336843, 1.73433184,
        1.60644897, 1.36533615, 1.16348921, 1.10052934, 1.7259592 ],
       [1.40470299, 0.74984746, 1.18620079, 1.45863646, 1.33151082,
        0.94845308, 1.32667592, 1.12178991, 0.88359647, 1.28279559],
       [2.06566177, 1.42083248, 1.9197561

In [6]:
p , q, b = gradient(data, p, q, b)
p


array([[0.49529088, 0.43459125],
       [0.23035426, 0.27476142],
       [0.78408535, 0.86761061],
       [0.62682079, 0.2690548 ],
       [0.6849995 , 0.46068284],
       [0.69031401, 0.76549807],
       [0.09639544, 0.20875957],
       [0.23354067, 0.26616205],
       [0.98864654, 0.87351438],
       [0.09924667, 0.77152565]])

In [20]:
for _ in range(1000):
    p, q, b= gradient(data, p, q, b)
    

In [21]:
comput_cost(data, p, q, b)


1.701511494082473e-13

In [22]:
data

array([[2, 4, 3, 1, 4, 0, 0, 3, 3, 3],
       [1, 2, 3, 0, 0, 2, 3, 4, 3, 4],
       [2, 2, 2, 2, 1, 2, 0, 1, 1, 4],
       [0, 3, 3, 1, 2, 0, 2, 3, 3, 4],
       [3, 1, 0, 0, 4, 3, 3, 2, 3, 4],
       [2, 3, 0, 4, 2, 3, 3, 4, 3, 0],
       [0, 0, 3, 3, 2, 2, 4, 0, 2, 2],
       [3, 4, 1, 1, 0, 3, 4, 3, 2, 2],
       [0, 4, 4, 1, 3, 3, 2, 4, 0, 1],
       [4, 3, 1, 0, 0, 2, 3, 2, 2, 3]])

In [23]:
p@q.T + b


array([[ 2.00000022e+00,  4.00000060e+00,  2.99999922e+00,
         1.00000060e+00,  3.99999930e+00,  2.90261685e-07,
        -1.34777596e-07,  2.99999992e+00,  2.99999991e+00,
         2.99999998e+00],
       [ 1.00000006e+00,  2.00000008e+00,  2.99999923e+00,
         4.13064229e-07, -9.03049912e-07,  1.99999982e+00,
         2.99999964e+00,  3.99999993e+00,  3.00000067e+00,
         3.99999983e+00],
       [ 2.00000014e+00,  2.00000041e+00,  1.99999966e+00,
         2.00000031e+00,  9.99999756e-01,  2.00000026e+00,
         7.08909920e-09,  9.99999960e-01,  9.99999744e-01,
         4.00000003e+00],
       [ 9.39374014e-08,  3.00000020e+00,  2.99999930e+00,
         1.00000042e+00,  1.99999923e+00, -4.76516120e-08,
         1.99999973e+00,  2.99999993e+00,  3.00000042e+00,
         3.99999988e+00],
       [ 3.00000034e+00,  1.00000097e+00, -7.59331098e-07,
         7.16442524e-07,  3.99999947e+00,  3.00000063e+00,
         3.00000004e+00,  1.99999991e+00,  2.99999934e+00,
         4.

In [40]:
data

array([[ 1.,  3.,  0.,  3.,  3.,  3.,  3.,  1.,  1.,  0.],
       [ 1.,  1., nan,  1.,  3.,  1.,  1.,  4.,  0.,  3.],
       [ 0.,  0.,  2.,  1.,  0.,  4.,  4.,  4.,  0.,  4.],
       [ 2.,  0.,  3.,  4.,  1.,  0.,  0.,  3.,  1.,  1.],
       [ 3.,  1.,  2.,  0.,  3.,  4., nan,  2.,  1.,  1.],
       [ 2.,  0.,  4.,  0.,  1.,  3.,  4.,  2.,  1.,  3.],
       [ 1.,  4.,  0.,  3.,  4.,  0.,  1.,  1.,  4.,  2.],
       [ 0.,  2.,  1.,  2.,  1.,  1.,  3.,  4.,  3.,  4.],
       [ 1.,  4.,  2.,  1.,  3.,  1.,  0.,  3.,  2.,  0.],
       [ 3.,  1.,  2.,  1.,  1.,  2.,  3.,  1.,  4.,  3.]])

In [29]:
p.shape

(10, 2)

In [8]:
import numpy as np
from numpy.linalg import svd

data = np.random.randint(5, size=(10, 10)).astype(float)

data[1, 2] = np.nan
data[4, 6] = np.nan
data[7, 8] = np.nan
data[9, 0] = np.nan


In [9]:
data_copy = np.copy(data)
data_copy[1, 2] = 0
data_copy[4, 6] = 0
data_copy[7, 8] = 0
data_copy[9, 0] = 0


In [10]:
# generate random data with some null values

def comput_cost(data, p, q):
    mask = ~np.isnan(data)
    return np.sum(np.sum(((data - (p@q.T))**2)[mask])) + beta * np.sum(abs(p))**2 + beta * np.sum(abs(q))**2

def gradient(data, p, q ,k=5):
    p_new = np.copy(p)
    q_new = np.copy(q)
    for i in range(data.shape[0]):
        for j in range(data.shape[1]):
            if not np.isnan(data[i, j]):
                e_ij = 2 * (data[i, j] - np.dot(p_new[i, :], q_new[j, :].T))
                p_new[i, :] += alpha * (e_ij * q_new[j, :] + beta * p_new[i, :])
                q_new[j, :] += alpha * (e_ij * p_new[i, :] + beta * q_new[j, :])
                
    return p_new, q_new

# u, s, vh = svd(data_copy)
# p = u
# q = np.matmul(np.diag(s), vh)

p = np.random.normal(0, 1, size=(10, 10))
q = np.random.normal(0, 1, size=(10, 10))

alpha = 0.001
beta = 0.001

p , q = gradient(data, p, q)
for _ in range(5000):
    p, q = gradient(data, p, q)

cost = comput_cost(data, p, q)
print("Final cost:", cost)
result = p@q.T
print("Factorization result:", result)


Final cost: 12.793449329952114
Factorization result: [[ 1.00869251e+00  3.00514261e+00 -1.21931144e-03 -6.89411019e-03
   9.98859928e-01  3.99898663e+00  1.99826977e+00  2.00155915e+00
   1.00325744e+00  2.00007166e+00]
 [ 2.01088915e+00  1.00061569e+00 -2.07287461e+00  2.99442248e+00
   9.98322471e-01  9.97586006e-01  2.99926002e+00  9.63222982e-05
   3.00686668e+00  3.99842814e+00]
 [ 9.93276604e-01 -2.68551307e-03  7.48643785e-04  1.00669605e+00
   3.00295091e+00  2.00144458e+00  1.00032531e+00  4.00115293e+00
   9.95357324e-01  1.90305594e-03]
 [ 1.00705138e+00  2.00227485e+00  1.99998421e+00  3.99658607e+00
   1.99941026e+00  1.99829852e+00  9.98259564e-01  4.00264406e+00
   4.00436335e+00  2.99953303e+00]
 [-3.10859244e-04  4.00126548e+00  4.00114825e+00  1.00037288e+00
   4.00130034e+00  3.00081658e+00  8.62144615e-01  9.99654239e-01
   4.00120357e+00  1.99911390e+00]
 [ 9.85318826e-01  3.99822414e+00 -2.50819518e-04  4.01218994e+00
   2.33845677e-03  2.00499578e+00  3.00193332e

In [11]:
data


array([[ 1.,  3.,  0.,  0.,  1.,  4.,  2.,  2.,  1.,  2.],
       [ 2.,  1., nan,  3.,  1.,  1.,  3.,  0.,  3.,  4.],
       [ 1.,  0.,  0.,  1.,  3.,  2.,  1.,  4.,  1.,  0.],
       [ 1.,  2.,  2.,  4.,  2.,  2.,  1.,  4.,  4.,  3.],
       [ 0.,  4.,  4.,  1.,  4.,  3., nan,  1.,  4.,  2.],
       [ 1.,  4.,  0.,  4.,  0.,  2.,  3.,  1.,  4.,  4.],
       [ 0.,  1.,  4.,  1.,  0.,  2.,  1.,  1.,  3.,  2.],
       [ 3.,  0.,  1.,  2.,  4.,  4.,  3.,  2., nan,  0.],
       [ 4.,  2.,  3.,  4.,  0.,  3.,  4.,  2.,  2.,  3.],
       [nan,  3.,  3.,  2.,  1.,  2.,  4.,  3.,  1.,  2.]])

In [13]:
p.shape

(10, 10)

In [14]:
q.shape

(10, 10)